apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-chart.fullname" . }}
  labels:
    {{- include "web-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}  # Đảm bảo rằng NodePort nằm trong dải cổng NodePort hợp lệ
  selector:
    {{- include "web-chart.selectorLabels" . | nindent 4 }}
